# Generated by Django 3.2.9 on 2021-11-27 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('img', models.ImageField(upload_to='photo')),
                ('des', models.CharField(max_length=50)),
            ],
        ),
    ]
