# Generated by Django 3.2.9 on 2021-11-27 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0002_auto_20211127_1448'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='watch',
            new_name='watches',
        ),
    ]
